# .github/workflows/ci.yml

name: Ruby Gem CI (PostgreSQL)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3'] # Adjust as needed

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: yantra_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # Runs bundle install

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      # Install gem dependencies (handled by bundler-cache: true)

      - name: Set up test database
        env:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: password
        # --- UPDATED: Use bin/rails instead of bundle exec ---
        run: |
          bin/rails db:create db:schema:load RAILS_ENV=test
        # --- END UPDATE ---
        working-directory: test/dummy # Keep running inside dummy app directory

      - name: Run tests
        env:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: password
        run: bundle exec rake test # Rake test likely still run from root


