# .github/workflows/ci.yml

name: Ruby Gem CI (PostgreSQL)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }} CI Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3'] # Test only compatible versions

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: yantra_test # Ensure this matches your dummy app's database.yml
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Map container port 5432 to host port 5432
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          # Cache gems using bundler, runs `bundle install` from the root
          # This caches gems based on the ROOT Gemfile.lock
          bundler-cache: true

      - name: Install system dependencies (for pg gem)
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Set up test database
        env:
          RAILS_ENV: test
          # Point Rails to the service container
          PGHOST: 127.0.0.1 # Use localhost/127.0.0.1 because of port mapping
          PGPORT: 5432 # The host port mapped from the container
          PGUSER: postgres
          PGPASSWORD: password
        # Change directory to the dummy app first
        working-directory: test/dummy
        run: |
          echo "Current directory: $(pwd)" # Should be test/dummy
          # --- UPDATED: Run bundle install inside test/dummy ---
          # Install gems specific to the dummy app's Gemfile
          bundle install
          # --- END UPDATE ---
          # Now, use bundle exec to run the rails command from installed gems
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          # Also ensure test environment uses the correct DB connection details
          PGHOST: 127.0.0.1
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: password
        # Run tests from the project root (assuming rake tasks handle the dummy app context)
        # If tests need to be run from test/dummy, add working-directory here too.
        run: bundle exec rake test


